name: Node CI
on:
  create:
    tags:
      - v*
jobs:
  build:
    name: Run Ubuntu
    runs-on: ubuntu-latest
    steps:
    - name: Checkout master branch
      uses: actions/checkout@master
    - name: Set-up Node.js 10.x
      uses: actions/setup-node@master
      with:
        version: 10.x
    - name: Install NPM dependencies and Firebase Tools
      run: |
        npm install
        npm install -g firebase-tools
    - name: Build
      run: |
        npm run build --if-present
    - name: Deploy
      run: |
        firebase deploy --token "${{ secrets.FIREBASE_TOKEN }}" -f
